apiVersion: v1
kind: ConfigMap                     # Mysql custom configuration
metadata:
  name: mysql-custom-config
data:
  mysql.cnf: |
    !includedir /etc/mysql/conf.d/
    !includedir /etc/mysql/mysql.conf.d/
    [mysqld]
    character-set-server=utf8
    collation-server=utf8_general_ci
    sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-db-option
data:
  change-db-option.sh: |-
    echo "ALTER DATABASE melisplatform CHARACTER SET utf8 COLLATE utf8_general_ci;" | mysql --host=localhost --user=root --password=$MYSQL_ROOT_PASSWORD
