services:
  php:
    platform: linux/amd64
    env_file: ./.env
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    # Mount the parent directory of where this repo is cloned
    volumes: ["../../../:/var/www/melis"]
    environment:
      MELIS_PLATFORM: ${MELIS_PLATFORM}
      MELIS_MODULE: ${MELIS_MODULE}
    networks:
      - melis
  db:
    image: mysql:${MYSQL_VERSION}
    platform: linux/amd64
    env_file: ./.env
    volumes:
      - melis_mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:${MYSQL_PORT}"
    environment:
      MYSQL_HOSTNAME: ${MELIS_CONTAINER_NAME}-db:${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
      ]
    networks:
      - melis

networks:
  melis:
volumes:
  melis_mysql_data:
