version: '3.2'
services:
  melisdocker:
    build:
       context: "."
       args:
          - tag=${tag}
    container_name: ${MELIS_CONTAINER_NAME}
    restart: always
    ports:
      - ${MELIS_PLATFORM_PORT}:80
    volumes:
      - ./conf/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    environment:
        MYSQL_ADDON_DB: ${MYSQL_ADDON_DB}
        MYSQL_ADDON_HOST: ${MYSQL_ADDON_HOST}
        MYSQL_ADDON_USER: ${MYSQL_ADDON_USER}
        MYSQL_ADDON_PASSWORD: ${MYSQL_ROOT_PASS}
    networks:
      - front
      - back
  db:
    image: mysql:${MYSQL_VERSION}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    environment:
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
         MYSQL_DATABASE: ${MYSQL_DB}
    networks:
      - back
    volumes:
      - melis_mysql_data:/var/lib/mysql  
networks:
  front: 
  back:
volumes:
  melis_mysql_data: