name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  php73:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: debug docker hub login
      run: echo ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build the Docker image php7.3
      run: docker build . --file dev/php-apache-7.3/Dockerfile --tag melisplatform/melis-docker:dev-apache-7.3
    - name: psuh image php7.3 to docker hub
      run: docker push melisplatform/melis-docker:dev-apache-7.3
